# Generated by Django 3.2.14 on 2022-08-03 07:08

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karusel', '0005_auto_20220621_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karusel',
            options={'verbose_name': 'Бош саҳифа мавзуси', 'verbose_name_plural': 'Бош саҳифа мавзуси'},
        ),
        migrations.AlterModelOptions(
            name='karuselimages',
            options={'verbose_name': 'Карусел расми', 'verbose_name_plural': 'Карусел расмлари'},
        ),
        migrations.AlterField(
            model_name='karusel',
            name='title',
            field=models.TextField(verbose_name='Мавзу'),
        ),
        migrations.AlterField(
            model_name='karusel',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Мавзу'),
        ),
        migrations.AlterField(
            model_name='karusel',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='Мавзу'),
        ),
        migrations.AlterField(
            model_name='karusel',
            name='title_uz',
            field=models.TextField(null=True, verbose_name='Мавзу'),
        ),
        migrations.AlterField(
            model_name='karusel',
            name='title_uzb',
            field=models.TextField(null=True, verbose_name='Мавзу'),
        ),
        migrations.AlterField(
            model_name='karuselimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='KoruselImages', validators=[config.utils.imagefile_validation_exception], verbose_name='Расмлар'),
        ),
    ]
